package com.evanhoe.tango.objs;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_INFO".
 */
public class PersonInfo {

    private String PersonID;
    private String GroupID;
    private String GroupName;
    private String FirstName;
    private String LastName;
    private String UserRoleCode;
    private String UserSubRoleCode;
    private String RemoteValidationRequired;
    private String CanCompleteTrainingSWO;
    private String CurrentMobileAppVersionNumber;

    public PersonInfo() {
    }

    public PersonInfo(String PersonID, String GroupID, String GroupName, String FirstName, String LastName, String UserRoleCode, String UserSubRoleCode, String RemoteValidationRequired, String CanCompleteTrainingSWO, String CurrentMobileAppVersionNumber) {
        this.PersonID = PersonID;
        this.GroupID = GroupID;
        this.GroupName = GroupName;
        this.FirstName = FirstName;
        this.LastName = LastName;
        this.UserRoleCode = UserRoleCode;
        this.UserSubRoleCode = UserSubRoleCode;
        this.RemoteValidationRequired = RemoteValidationRequired;
        this.CanCompleteTrainingSWO = CanCompleteTrainingSWO;
        this.CurrentMobileAppVersionNumber = CurrentMobileAppVersionNumber;
    }

    public String getPersonID() {
        return PersonID;
    }

    public void setPersonID(String PersonID) {
        this.PersonID = PersonID;
    }

    public String getGroupID() {
        return GroupID;
    }

    public void setGroupID(String GroupID) {
        this.GroupID = GroupID;
    }

    public String getGroupName() {
        return GroupName;
    }

    public void setGroupName(String GroupName) {
        this.GroupName = GroupName;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getUserRoleCode() {
        return UserRoleCode;
    }

    public void setUserRoleCode(String UserRoleCode) {
        this.UserRoleCode = UserRoleCode;
    }

    public String getUserSubRoleCode() {
        return UserSubRoleCode;
    }

    public void setUserSubRoleCode(String UserSubRoleCode) {
        this.UserSubRoleCode = UserSubRoleCode;
    }

    public String getRemoteValidationRequired() {
        return RemoteValidationRequired;
    }

    public void setRemoteValidationRequired(String RemoteValidationRequired) {
        this.RemoteValidationRequired = RemoteValidationRequired;
    }

    public String getCanCompleteTrainingSWO() {
        return CanCompleteTrainingSWO;
    }

    public void setCanCompleteTrainingSWO(String CanCompleteTrainingSWO) {
        this.CanCompleteTrainingSWO = CanCompleteTrainingSWO;
    }

    public String getCurrentMobileAppVersionNumber() {
        return CurrentMobileAppVersionNumber;
    }

    public void setCurrentMobileAppVersionNumber(String CurrentMobileAppVersionNumber) {
        this.CurrentMobileAppVersionNumber = CurrentMobileAppVersionNumber;
    }

}
